# Generated by Django 2.2.7 on 2019-11-08 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seafarer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(max_length=6)),
                ('nationality', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SeafarerCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_code', models.CharField(max_length=50)),
                ('date_of_issue', models.DateField(default=django.utils.timezone.now)),
                ('date_of_expiry', models.DateField(default=django.utils.timezone.now)),
                ('name_issuing_institute', models.CharField(max_length=100)),
                ('name_issuing_country', models.CharField(max_length=100)),
                ('date_of_last_revalidation', models.DateField(default=django.utils.timezone.now)),
                ('dispensation_details', models.TextField()),
                ('certificate_status', models.CharField(max_length=10)),
                ('certificate_scanned_copy', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.Certificate')),
                ('seafarer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seafarers.Seafarer')),
            ],
        ),
    ]
