# Generated by Django 2.2.7 on 2019-11-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafarers', '0003_auto_20191113_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seafarercertificate',
            name='certificate_barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
